/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class linearLayer */

#ifndef _Included_linearLayer
#define _Included_linearLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     linearLayer
 * Method:    init
 * Signature: (Ljava/lang/String;II)LlinearLayer;
 */
JNIEXPORT jobject JNICALL Java_linearLayer_init
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     linearLayer
 * Method:    forward
 * Signature: ([F[F[F[FIIII)V
 */
JNIEXPORT void JNICALL Java_linearLayer_forward
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint, jint, jint, jint);

/*
 * Class:     linearLayer
 * Method:    backprop
 * Signature: ([FF)V
 */
JNIEXPORT void JNICALL Java_linearLayer_backprop
  (JNIEnv *, jobject, jfloatArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
